#!/bin/sh
# -*- sh -*-
#
# Plugin to tomcat webapp sessions.
#
# Parameters:
#
#       config   (required)
#       autoconf (optional - only used by munin-config)
#
#
# Magic markers (optional - used by munin-config and some installation
# scripts):
#%# family=auto
#%# capabilities=autoconf

if [ "${url}" = "" ]; then
        export url=http://localhost:8080/munin/plugin
fi


if [ "$1" = "autoconf" ]; then
        wget -q -O - ${url}?a=autoconf
        exit 0
fi

if [ "$1" = "config" ]; then
        wget -q -O - ${url}?g=sessions\&a=config
        exit 0
fi

wget -q -O - ${url}?g=sessions\&a=value
exit 0
